config/routes.rb
Rails.application.routes.draw do
  get 'products/index'

  get 'postcomments/new'

  get 'images/new'

  get 'posts/index'

  get 'userparams/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'

  devise_for :users

resources :userparams

  resources :posts do
  	resources :postcomments
  	resources :images
  end

root to: 'pages#index'

  resources :products
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :posts
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :image, ImageUploader
    belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	belongs_to :category
			validates :name, :year, :price, :ks, :privod, :kuzov, presence: true
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :text, length: { in: 1..25}
	validates :text, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :icons, IconUploader
  serialize :icons, JSON

  belongs_to :user
  validates :name, :price, :count, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_one :userparam 
    has_many :postcomments
    has_many :products, dependent: :destroy     
end

app/models/userparam.rb
class Userparam < ApplicationRecord
	mount_uploader :avatar, AvatarUploader

	belongs_to :user

	validates :firstname, :lastname, presence: true

    validates :phone,
               uniqueness: true,
               length: { is: 13 },
               format: {with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/}	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
before_action :authenticate_user!
def create
params[:postcomment][:post_id] = params[:post_id]
params[:postcomment][:user_id] = current_user.id
@comment = Postcomment.create(postcomments_params)
if @comment.save
redirect_to post_path(params[:post_id])
else
	@comment.errors.full_messages.each do |msg|
		@msg=msg
end
flash[:notice] = "#{@msg}"
redirect_to post_path(params[:post_id])
end
end

private

def postcomments_params
params.require(:postcomment).permit(:user_id, :post_id, :text)
end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :set_post, only: [:edit, :update, :destroy, :show]

def show
	@images = Image.where(post_id: @post.id)
	@comments = Postcomment.where(post_id: @post.id)
end

def index
@posts = Post.all
@posts.each do |post|
end

end

def new
@post = Post.new
end

def create
params[:post][:category_id] = params[:category_id]
params[:post][:post]
@post = Post.create(post_params)
redirect_to posts_path
end


private

def post_params
params.require(:post).permit(:category_id, :name, :year, :count, :price, :ks, :privod, :kuzov)
end

def set_post
@post = Post.find(params[:id])
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!, except: [:show]
before_action :set_product, only: [:edit, :update, :destroy, :show]

  def index
      @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(products_params)
    if @product.save
      redirect_to root_path
    end
  end

  def edit
  end

  def update
  end

private
  def products_params
    params.require(:product).permit(:user_id, :name, :description, :price, :count, {icons: []})
  end
def set_product
@product = Product.find(params[:id])
end



end

app/controllers/userparams_controller.rb
class UserparamsController < ApplicationController
before_action :authenticate_user!
before_action :get_userparam, except: [:new, :create]

  def index
    if @userparam.nil?
      redirect_to new_userparam_path
    else
      redirect_to userparam_path(@userparam.id)
    end
  end

  def show
    @user = Userparam.find(current_user.id)
  end
  
  def new
    @userparam = Userparam.new
  end
  
  def create
    @userparam = current_user.build_userparam(userparams_params)
    if @userparam.save    
      redirect_to userparam_path(@userparam.id)
    end
  end
  
  def edit
  end
  
  def update
    @userparam.update(userparams_params)
    redirect_to userparam_path(@userparam.id)
  end
  
private

  def userparams_params
    params.require(:userparam).permit(:user_id, :firstname, :lastname, :country, :city, :dofb, :avatar, :phone)
  end
  
  def get_userparam
    @userparam = Userparam.find_by(user_id: current_user.id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/views/images/new.html.erb
<h1>Images#new</h1>
<p>Find me in app/views/images/new.html.erb</p>

app/views/postcomments/new.html.erb
<h1>Postcomments#new</h1>
<p>Find me in app/views/postcomments/new.html.erb</p>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'animate' %>


<div class="wow bounceInDown" data-wow-delay="0.8s" data-wow-offset="20"><center><img src="http://cache.bmwusa.com/image_b361b59a-95b3-41a6-a2f2-a43d2f12aa8c.arox?v=c0597b06-dd62-447a-a4fe-69bf52f73922" alt="BMW_TOP"></center></div>
<div class="d7 wow rubberBand" data-wow-delay="2s" data-wow-offset="20"><h1 class="choosebmw">Вибери свою BMW!</h1></div>
<div class="cars">
<% @posts.each do |post| %>
<%= link_to post_path(post.id) do %>
	<div class="carelem">
	<p><%= image_tag(post.photo_url, :class => "carphoto")%></p>
	<p><center><%= link_to post.name,  post_path(post.id), :class => "detali"%></center></p>
	</div>
<% end %>
<% end %>
</div>


<%= javascript_include_tag 'wow.min'%>
<script>
  	new WOW().init();
</script>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'animate' %>

<h1 class="showcarname"><%= @post.name %></h1>
<div class="elements">
<div class="showelem1"><%= image_tag(@post.photo, :class => "showcar") %></div>
<div class="showelem2 wow fadeInRight" data-wow-delay="0.6s" data-wow-offset="20">
<h2 class="char"><center>Характеристики:</center></h2>

<div class="chars">
<p>Рік випуску: <%= @post.year %></p>
<p>Привод: <%= @post.privod %></p>
<p>Ціна: <%= @post.price %></p>
<p>Кінські сили: <%= @post.ks %></p>
<p>Тип кузова: <%= @post.kuzov %></p>
</div>


</div>
</div>
<h4 class="cartext"><%= @post.text %></h4>
<% if @images == [] %>

<% else %>
<div class="container">


  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
   <% @images.each_with_index do |image, n| %>
     <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
   <% end %>
</ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <p><%= image_tag(@images.first.image, :class => "imagecars") %></p>
      </div>


      <% @images.drop(1).each do |image| %>
      <div class="item">
        <p><%= image_tag(image.image, :class => "imagecars") %></p>
      </div>
      <hr>
      <% end %>
      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
      </div>
  </div>
</div>

<% end %>



<% @comments.each do |comment| %>
<p> User <b style="color:#0489B1"><%= comment.user.nickname %></b></p>
<p><%= comment.text %></p>
<p>Create at: <%= comment.created_at%>
</p>
<hr>
<% end %>


<%= form_for :postcomment, url: post_postcomments_path(post_id: @post.id) do |f| %>
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>

<p><%= f.label "Write comment" %></p>
<div class="textareadiv"><%= f.text_area :text, cols: 20, rows: 5, :class => "textarea" %></div><br />

<p><%= f.submit "Send"%></p>

<% end %>

<%= javascript_include_tag 'wow.min'%>
<script>
  	new WOW().init();
</script>

app/views/products/_form.html.erb
<div class="contact">
    <form action="#">
        <fieldset>
            <div class="row">
                <section class="col col-2">
                    <label class="input">
                        <p> Марка та модель авто</p>
                        <i class="fa fa-append fa-user"></i>
                        <%= f.text_field :name %>
                    </label>
                </section>
                <section class="col col-2">
                    <label class="input">
                        <p>Рік випуску</p>
                        <i class="fa fa-append fa-user"></i>
                        <%= f.text_field :count %>
                    </label>
                </section>
                <section class="col col-2">
                    <label class="input">
                        <p> Ціна</p>
                        <i class="fa fa-append fa-envelope-o"></i>
                        <%= f.text_field :price %>
                    </label>
                </section>
                <section class="col col-2">
                  <div class="image-upload">
                     <label for="file-input">
                       <div class="addphoto">
                          Додати фото
                       </div>
                     </label>
                     <%= f.file_field :icons, multiple: true, id:"file-input" %>
                  </div>
                </section>
            </div>
            <section>
                <label class="textarea">
                    <p>Опис автомобіля</p>
                    <%= f.text_area :description, :rows => 4 %>
                </label>
            </section>
            <button type="submit" class="button">Додати</button>
        </fieldset>
    </form>
</div>

app/views/products/index.html.erb
<center><img src="https://www.autopartmax.com/images/cUpload/bmw.png"><center>
  <h1 class="choosebmw">Немає грошей на нове авто? Вибирай б/у!</h1>
<p class="description-site">Всі автомобілі, які розміщені нижче ВЖИВАНІ. Автосалон не несе відповідальності за їх технічний стан. </p>
<div class="cars">
<% @products.each do |product| %>
<%= link_to product_path(product.id) do %>
<div class="carelem">
              <% if product.icons == [] %>
              <%= image_tag("default-img.png", height: '280', width: 'auto') %>

              <% else %>
                  <%= image_tag(product.icons.first.url, class: 'carphoto') %>
              <% end %>
                  <p><center><%= link_to product.name, product_path(product.id), class: 'detali'%></center></p>

                <div class="product_price"><%= product.price %>$</div>

</div>
      <% end %>
      <% end %>
</div>

app/views/products/new.html.erb
<%= form_for @product, url: products_path, validate: true do |f| %>

<%= render 'form', f: f %>

<% end %>

app/views/products/show.html.erb
<div class="contact12">
  <% if @product.icons == [] %>
  <form action="#">
      <fieldset>
          <div class="row">
              <section class="col col-2">
                  <label class="input">
                      <p style="text-align: center"> Марка та модель авто</p>
                      <div style="font-weight: bold;"><center><%= @product.name %></center></div>
                  </label>
              </section>
              <section class="col col-2">
                  <label class="input">
                      <p style="text-align: center">Рік випуску</p>
                      <div style="font-weight: bold;"><center><%= @product.count %></center></div>
                  </label>
              </section>
              <section class="col col-2">
                  <label class="input">
                      <p style="text-align: center"> Ціна</p>
                      <div style="font-weight: bold;"><center><%= @product.price %></center></div>
                  </label>
              </section>
          </div>
          <section>
              <label class="textarea">
                  <p>Опис автомобіля</p>
                  <%= @product.description %>
              </label>
          </section>
      </fieldset>
  </form>
  <% else %>

  <div class="container9">


    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
     <% @product.icons.each_with_index do |photo, n| %>
       <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
     <% end %>
  </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <p><%= image_tag(@product.icons.first.url, :class => "imagecars") %></p>
        </div>


        <% @product.icons.drop(1).each do |image| %>
        <div class="item">
          <p><%= image_tag(image, :class => "imagecars") %></p>
        </div>
        <hr>
        <% end %>
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
        </div>
    </div>
  </div>
    <form action="#">
        <fieldset>
            <div class="row">
                <section class="col col-2">
                    <label class="input">
                        <p style="text-align: center"> Марка та модель авто</p>
                        <div style="font-weight: bold;"><center><%= @product.name %></center></b></div>
                    </label>
                </section>
                <section class="col col-2">
                    <label class="input">
                        <p style="text-align: center">Рік випуску</p>
                        <div style="font-weight: bold;"><center><%= @product.count %></center></div>
                    </label>
                </section>
                <section class="col col-2">
                    <label class="input">
                        <p style="text-align: center"> Ціна</p>
                        <div style="font-weight: bold;"><center><%= @product.price %></center></div>
                    </label>
                </section>
            </div>
            <section>
                <label class="textarea">
                    <p style="text-align: center">Опис автомобіля</p>
                    <center><%= @product.description%></center>
                </label>
            </section>
        </fieldset>
    </form>
</div>
<% end %>

app/views/userparams/_form.html.erb
  <div class="contact">
    <div class="shapka">
        <%= image_tag 'https://i2.wp.com/2mprogress.com/wp-content/uploads/2017/11/person-1824144_1280.png', alt: 'Icon', size: "120x120", class: "iconka" %>
    </div>
    <form action="#">
        <fieldset>
            <div class="row">
                <section class="col col-2">
                    <label class="input">
                        <%= f.text_field :firstname, placeholder: "Ім'я", autofocus: true %>
                    </label>
                </section>
                <section class="col col-2">
                    <label class="input">
                        <%= f.text_field :lastname, placeholder: "Прізвище" %>
                    </label>
                </section>
                <section class="col col-2">
                    <label class="input">
                        <%= f.text_field :country, placeholder: "Країна" %>
                    </label>
                </section>
                <section class="col col-2">
                    <label class="input">
                        <%= f.text_field :city, placeholder: "Місто" %>
                    </label>
                </section>
                <section class="col col-2">
                    <label class="input">
                        <%= f.text_field :phone, placeholder: "Номер телефона" %>
                    </label>
                </section>
                <section class="col col-2">
                  <div class="image-upload">
                     <label for="file-input">
                       <div class="form1but">
                          Аватар
                       </div>
                     </label>
                     <%= f.file_field :avatar, id:"file-input" %>
                  </div>
                </section>
            </div>
            <section class="col col-2">
                <label class="input">
                    <%= date_select("userparam", "dofb", start_year: 1950, end_year: 2000, order: [:month, :day, :year]) %>
                </label>
            </section>
            <button type="submit" class="button">Зберегти</button>
        </fieldset>
    </form>
</div>

app/views/userparams/edit.html.erb
<%= form_for @userparam, validate: true, url: userparam_path(@userparam.id), method: :patch do |f| %>

<%= render 'form', f: f %>
  
<% end %>

app/views/userparams/new.html.erb
<%= form_for @userparam, url: userparams_path, validate: true do |f| %>

<%= render 'form', f: f %>
 
<% end %>

app/views/userparams/show.html.erb
<div class="contact">
  <div class="shapka">
      <%= image_tag 'https://i2.wp.com/2mprogress.com/wp-content/uploads/2017/11/person-1824144_1280.png', alt: 'Icon', size: "120x120", class: "iconka" %>
  </div>
  <form action="#">
      <fieldset>
          <section>
            <center><p style="font-size: 48px; padding-bottom: 15px;">Профіль</p></center>
            <center><%= image_tag(@user.avatar, class: 'avatarka')  %></center>
          <div class="row">
              <section class="col col-2">
                 <p>Ім'я: <%= @user.firstname %></p>
              </section>
              <section class="col col-2">
                      <p>Прізвище: <%= @user.lastname %></p>
              </section>
              <section class="col col-2">
                  <p>Країна: <%= @user.country %></p>
              </section>
              <section class="col col-2">
                  <p>Місто: <%= @user.city %></p>
              </section>
              <section class="col col-2">
                  <p>Дата народження: <%= @user.dofb.strftime("%b,%d,%Y") %></p>
              </section>
              <section class="col col-2">
                  <p>Телефон: <%= @user.phone %></p>
              </section>

          </div>

          <%= link_to "Редагувати", edit_userparam_path, class: 'form2but' %>
      </fieldset>
  </form>
</div>