config/routes.rb
Rails.application.routes.draw do
  get 'products/index'

  get 'postcomments/new'

  get 'images/new'

  get 'posts/index'

  get 'userparams/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'

  devise_for :users

resources :userparams

  resources :posts do
  	resources :postcomments
  	resources :images
  end

root to: 'pages#index'

  resources :products
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :posts
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :image, ImageUploader
    belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	belongs_to :category
			validates :name, :year, :price, :ks, :privod, :kuzov, presence: true
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :text, length: { in: 1..25}
	validates :text, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :icons, IconUploader
  serialize :icons, JSON

  belongs_to :user
  validates :name, :price, :count, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_one :userparam 
    has_many :postcomments
    has_many :products, dependent: :destroy     
end

app/models/userparam.rb
class Userparam < ApplicationRecord
	mount_uploader :avatar, AvatarUploader

	belongs_to :user

	validates :firstname, :lastname, presence: true

    validates :phone,
               uniqueness: true,
               length: { is: 13 },
               format: {with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/}	
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :set_post, only: [:edit, :update, :destroy, :show]

def show
	@images = Image.where(post_id: @post.id)
	@comments = Postcomment.where(post_id: @post.id)
end

def index
@posts = Post.all
@posts.each do |post|
end

end

def new
@post = Post.new
end

def create
params[:post][:category_id] = params[:category_id]
params[:post][:post]
@post = Post.create(post_params)
redirect_to posts_path
end


private

def post_params
params.require(:post).permit(:category_id, :name, :year, :count, :price, :ks, :privod, :kuzov)
end

def set_post
@post = Post.find(params[:id])
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!, except: [:show]
before_action :set_product, only: [:edit, :update, :destroy, :show]

  def index
      @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(products_params)
    if @product.save
      redirect_to root_path
    end
  end

  def edit
  end

  def update
  end

private
  def products_params
    params.require(:product).permit(:user_id, :name, :description, :price, :count, {icons: []})
  end
def set_product
@product = Product.find(params[:id])
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer-Section">
	<div class="footer-top-layout">
		<div class="container1">
			<div class="row">
				<div class="OurBlog">
					<h4>Автосалон "BMW-шечка"</h4>
					<p>Найкращі ціни для нових емоцій!</p>
					<div class="post-blog-date">Замовляй прямо зараз</div>
				</div>
				<div class=" col-lg-8 col-lg-offset-2">
					<div class="col-sm-4">
						<div class="footer-col-item">
							<h4>Наша адреса:</h4>
							<address>
							51,13 проспект Свободи<br>
							88015 Ужгород, Україна
							</address>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="footer-col-item">
							<h4>Зв'язок з нами:</h4>
							<div class="item-contact"> <a href="tel:630-885-9200"><span class="link-id">P</span>:<span>630-885-9200</span></a> <a href="tel:630-839.2006"><span class="link-id">F</span>:<span>630-839.2006</span></a> <a href="mailto:info@brandcatmedia.com"><span class="link-id">E</span>:<span>info@brandcatmedia.com</span></a> </div>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="footer-col-item">
							<h4>Будемо раді бачити вас в нашому автосалоні</h4>
							<p>Замовляй сьогодні, завтра драйвуй!</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-bottom-layout">

		<div class="copyright-tag">Copyright © 2017 © BMW AG 2017. All Rights Reserved.</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= link_to "Bimer Shop", root_path, class: "navbar-brand"%>
			<% if current_user.nil? %>
			<%= link_to "Нові авто",  posts_index_path, class: "navbar-brand"%>
      <%= link_to "Б/у авто", products_index_path, class: "navbar-brand"%>
			<%else%>

			<%= link_to "Нові авто",  posts_index_path, class: "navbar-brand"%>
      <%= link_to "Б/у авто", products_index_path, class: "navbar-brand"%>

			<%end%>


		</div>

		<ul class="nav navbar-nav navbar-right">
		<% if current_user.nil? %>

			<li>
				<%= link_to user_session_path, :class => "authin" do %></p>
					<i class="glyphicon glyphicon-user"></i><span class="authin"> Вхід </span>
				<% end %>
			</li>
			<% else %>
      <li>
        <%= link_to new_product_path, class: "navbar-brand" do %>
        <i class="zmdi zmdi-plus"></i> Додати власне авто
        <% end %>
      </li>
      <li>
        <%= link_to userparams_path, class: "navbar-brand" do%>
          Профіль
        <%end%>

      </li>
			<li>
				<%= link_to destroy_user_session_path, :class => "authin", method: :delete  do %>
					<i class="glyphicon glyphicon-log-in"></i><span class="authin"> Вихід </span>
				<% end %>
			</li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title>Bimershop</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="particles-js"></div>
  <%= javascript_include_tag 'particles', 'app'%>
  <div id="page-wrapper">
  	<%= render 'layouts/header'%>
	  <%= yield %>
	  <%= render 'layouts/footer'%>
  </div>


  </body>
</html>

app/views/pages/index.html.erb
<%= stylesheet_link_tag 'animate' %>

<div class="wow flipInX" data-wow-offset="10"><img src="assets/back1.png" alt="BimerShop" width="100%"></div>
<center><div class="button-container"><a href="/posts/index">Каталог</a></div></center>

<div >
  <p class="description-site">«Bimershop» - офіційний дилер відомого німецького виробника автомобілів - Bayerische Motoren Werke (BMW). У салоні «Bimershop» представлений весь модельний ряд автомобілів BMW, який дозволить вибрати автомобіль, відповідний найвищим вимогам комфорту і якості, що важливо при виборі автомобіля - за доступною ціною.

  Наш сервісний центр забезпечить Вам швидку, кваліфіковану допомогу і підтримку. Для цього є все необхідне устаткування, яке відповідає вимогам обслуговування саме цих автомобілів. Для забезпечення швидкого обслуговування є власний склад запасних частин, на якому є достатній запас ресурсів.</p>
</div>


<%= javascript_include_tag 'wow.min'%>
<script>
  	new WOW().init();
</script>